### ISSUE TITLE
Cannot open shared object file

### ISSUE THREAD

**Issue by realies** [1and1internet/ubuntu-16-nginx-php-7.1#13]
Everything works as expected but seeing this when running attached:

`Failed loading /usr/lib/php/20151012/ioncube_loader_lin_7.0.so:  /usr/lib/php/20151012/ioncube_loader_lin_7.0.so: cannot open shared object file: No such file or directory`

**Comment by astrolox** [comment]
Thank you for reporting this. 
This has been fixed now. 
A new build will be automatically pushed to dockerhub soon.
